accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views

app_name = 'accountapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/', views.testpage, name='testpage'),
]

handledb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dbmanageapp import views

urlpatterns = [
    path('', views.dbmainpage, name='home'),
    path('adminchangi/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('dbmanager/', include('dbmanageapp.urls')),
    path('super_adm/', include('allmanageapp.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

RATE_CHOICE = (('A', '마스터'), ('B', '관리자'), ('C', '부관리자'), ('D', '직원'))
STATUS_CHOICE = (('Y', '활동'), ('N', '비활동'))


class User(AbstractUser):
    rete = models.CharField(choices=RATE_CHOICE, max_length=20, null=False, default='D')
    nickname = models.CharField(max_length=20, null=False, default='', unique=True)
    status = models.CharField(choices=STATUS_CHOICE, max_length=5, null=False, default='Y')

accountapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('nickname',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

accountapp/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy

from accountapp.forms import LoginForm
from accountapp.models import User


def testpage(request):
    return render(request, 'accountapp/testpage.html', {'test': 'test'})


def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] != request.POST['password2']:
            error_message = {'error_nopass': '비밀번호가 일치하지 않습니다. 비밀번호를 확인해주세요'}
            return render(request, 'accountapp/signup.html', error_message)
        else:
            try:
                User.objects.create_user(username=request.POST['username'], password=request.POST['password1'], nickname=request.POST['nickname'], )
            except:
                error_message = {'error_noid': '이미 가입된 아이디 또는 닉네임 입니다.'}
                return render(request, 'accountapp/signup.html', error_message)

        user = authenticate(username=request.POST['username'], password=request.POST['password1'])
        login(request, user)
        return HttpResponseRedirect(reverse_lazy('home'))

    return render(request, 'accountapp/signup.html')


def signin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():  # form 검증
            username = form.cleaned_data['username']  # form에서 data 가져오기
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                # 참일경우
                login(request, user)
                return HttpResponseRedirect(reverse_lazy('home'))

        # 유효성 검증에 실패했을경우
        return render(request, 'accountapp/login.html', {'error': '아이디와 비밀번호를 확인해주세요'})
    else:
        form = LoginForm()
        return render(request, 'accountapp/login.html')

accountapp/templates/accountapp/login.html
{% extends 'account_base.html' %}

{% block accountcontent %}

<style>
    #layoutAuthentication_content{background-color:#0d6efd;}


</style>


<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-9 col-lg-6 mx-auto">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">로그인</h3></div>
                            <div class="card-body">
                                <form method="post">

                                    {% if error %}
                                    <div class="mt-1 mb-3" style="font-size:14px; color:red;">{{ error }}</div>
                                    {% endif %}
                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="inputUsername" type="username" name="username"
                                               placeholder="name@example.com"/>
                                        <label for="inputUsername">아이디를 입력하세요</label>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="inputPassword" type="password" name="password"
                                               placeholder="Password"/>
                                        <label for="inputPassword">비밀번호를 입력하세요</label>
                                    </div>
                                    <div style="text-align:right;">
                                        <input type="submit" class="btn btn-primary" value="로그인">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center py-3">
                                <div class="small"><a href="{% url 'accountapp:signup' %}">회원가입 바로가기</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

<button class="testbtn">
    asdfasdf
</button>

<script !src="">


</script>

{% endblock %}

accountapp/templates/accountapp/signup.html
{% extends 'account_base.html' %}

{% block accountcontent %}

<style>
    #layoutAuthentication_content{background-color:#0d6efd;}

</style>

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">회원가입!!!!</h3></div>
                            <div class="card-body">

                                <form method="post"">

                                    {% csrf_token %}
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="inputUsername" type="text" placeholder="id"
                                               name="username"/>
                                        <label for="inputUsername">아이디를 입력하세요</label>
                                    </div>
                                    <div>{{ error_noid }}</div>


                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="inputnickname" type="text" name="nickname"
                                               placeholder="name@example.com"/>
                                        <label for="inputEmail">닉네임을 입력하세요</label>
                                    </div>


                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input class="form-control" id="inputPassword" type="password"
                                                       name="password1" placeholder="Create a password"/>
                                                <label for="inputPassword">비밀번호</label>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input class="form-control" id="inputPasswordConfirm" type="password"
                                                       name="password2" placeholder="Confirm password"/>
                                                <label for="inputPasswordConfirm">비밀번호 확인</label>
                                            </div>
                                        </div>
                                        <div>{{ error_nopass }}</div>
                                    </div>
                                    <div class="mt-4 mb-0">
                                        <input type="submit" class="btn btn-primary btn-block w-100 chksubmit" value="계정 생성하기">
                                    </div>
                                </form>


                            </div>
                            <div class="card-footer text-center py-3">
                                <div class="small">
                                    <a href="{% url 'accountapp:login' %}">로그인 페이지 바로가기</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

<script type="text/javascript">

  $('.chksubmit').click(function(){
    var inputPassword = document.querySelector('#inputPassword')
    if(inputPassword.value.length < 4){
      alert('비밀번호가 너무 짧습니다! 4자리 이상으로 입력해주세요!')
      return false;
    }
  })

</script>

{% endblock %}

accountapp/templates/accountapp/testpage.html
{% extends 'account_base.html' %}

{% block accountcontent %}

{% if user.is_authenticated %}
    <p>이 유저는 로그인 되어 있습니다.</p>
{% endif %}

{% if user.is_anonymous %}
    <p>This user is logged out</p>
{% endif %}



{% endblock %}