dbmanageapp/urls.py
from django.urls import path

from dbmanageapp import views

app_name = 'dbmanage'
urlpatterns = [
    path('', views.dbmainpage, name='mainpage'),
    path('accountmanagement/', views.accountmanagement, name='accountmanagement'),
    path('markterlist/', views.markerlist, name='markerlist'),
    path('newdbup/', views.newdbup, name='newdbup'),
    path('new_dbup/', views.new_dbup, name='new_dbup'),
    path('divdb/', views.divdb, name='divdb'),
    path('alldblist/', views.alldblist, name='alldblist'),
    path('sale_st/', views.sale_st, name='sale_st'),
    path('detail_customer/<int:id>', views.detail_customer, name='detail_customer'),
    path('workajax/', views.workAjax, name='workajax'),

    path('emp_dblist/', views.emp_dblist, name='emp_dblist'),
    path('div_dbname/', views.div_dbname, name='div_dbname'),
    path('emp_dbstats/', views.emp_dbstats, name='emp_dbstats'),
    path('base_setting/', views.base_setting, name='base_setting'),
    path('marketer_stats/', views.marketer_stats, name='marketer_stats'),
    path('test_chk/', views.test_chk, name='test_chk'),
    path('status_stats/', views.status_stats, name='status_stats'),
    path('updatedb/', views.update_db, name='updatedb'),
    path('make_excel/', views.make_excel, name='make_excel'),

]

handledb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dbmanageapp import views

urlpatterns = [
    path('', views.dbmainpage, name='home'),
    path('adminchangi/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('dbmanager/', include('dbmanageapp.urls')),
    path('super_adm/', include('allmanageapp.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbmanageapp/models.py
from django.core.validators import RegexValidator
from django.db import models

ADV_CHOICE = (('cpa', 'CPA'), ('cpc', 'CPC'), ('cps', 'CPS'), ('cpv', 'CPV'), ('cpm', 'CPM'))
APPROV_CHOICE = (('Y', '거래'), ('N', '미거래'))
THEME_CHOICE = (('light', '라이트'), ('dark', '다크'))
# Create your models here.

class DbSetting(models.Model):
    ds_status = models.CharField(max_length=255, null=True, blank=True)
    ds_statusbase = models.CharField(max_length=20, null=True, blank=True, default='')
    ds_overlapallow = models.CharField(max_length=255, null=True, blank=True, default='')
    logo_image = models.ImageField(upload_to='setimage/', null=True, blank=True)
    company_name = models.CharField(max_length=255, null=True)
    theme_status = models.CharField(choices=THEME_CHOICE, max_length=5, null=False, default='dark')

class MarketingList(models.Model):
    mk_company = models.CharField(max_length=30, null=False)
    mk_name = models.CharField(max_length=10, null=True)
    phoneNumberRegex = RegexValidator(regex=r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
    mk_phone = models.CharField(validators=[phoneNumberRegex], max_length=11, null=True)
    mk_advtype = models.CharField(choices=ADV_CHOICE, max_length=5, null=True, default='cpa')
    mk_url = models.CharField(max_length=255, null=True)
    mk_memo = models.TextField(null=True)
    mk_status = models.CharField(choices=APPROV_CHOICE, max_length=5, null=False, default='Y')
    mk_date = models.DateTimeField(auto_now_add=True, null=True)

    # def __str__(self):
    #     return self.mk_company

class UploadDbName(models.Model):
    dbn_mkname = models.ForeignKey(MarketingList, on_delete=models.SET_NULL, null=True, related_name='mkdname')
    dbn_name = models.CharField(max_length=255, null=False)
    dbn_price = models.IntegerField(null=False)
    dbn_memo = models.CharField(max_length=255, null=True)
    dbn_date = models.DateTimeField(auto_now_add=True, null=True)

    # def __str__(self):
    #     return self.dbn_name


class UploadDb(models.Model):
    db_name = models.ForeignKey(UploadDbName, on_delete=models.SET_NULL, null=True, related_name='dbname')
    db_mkname = models.ForeignKey(MarketingList, on_delete=models.SET_NULL, null=True, related_name='dbmkname')
    db_phone = models.CharField(max_length=20, null=False)
    db_member = models.CharField(max_length=20, null=False)
    db_age = models.CharField(max_length=20, null=True, default='')
    db_sex = models.CharField(max_length=20, null=True, default='')
    db_inv = models.CharField(max_length=20, null=True, default='')
    db_manager = models.CharField(max_length=20, null=True)
    db_manager_nick = models.CharField(max_length=20, null=True)
    db_status = models.CharField(max_length=20, null=True, default='')
    db_paidprice = models.IntegerField(null=True, default='0', blank=True)
    db_paidstatus = models.CharField(max_length=5, null=True, default='N')
    db_lastpaiddate = models.DateTimeField(auto_now_add=True, null=True)
    db_date = models.DateTimeField(auto_now_add=True, null=True)
    # db_divdate = models.DateTimeField(auto_now_add=True, null=True)



    # def __str__(self):
    #     return self.db_member


class DbMemo(models.Model):
    dm_chkdb = models.ForeignKey(UploadDb, on_delete=models.CASCADE, null=False, related_name='dmchkdb', default='')
    dm_manager = models.CharField(max_length=50, null=True, default='')
    dm_memos = models.CharField(max_length=2550, null=False, default='')
    dm_date = models.DateTimeField(auto_now_add=True, null=False)


class PaidList(models.Model):
    pl_chkdb = models.ForeignKey(UploadDb, on_delete=models.CASCADE, null=False, related_name='plchkdb', default='')
    pl_paidprice = models.IntegerField(null=False, default='0', blank=False)
    pl_paiddate = models.DateTimeField(auto_now_add=True, null=False)


class TestField(models.Model):
    td_name = models.CharField(max_length=15)
    td_mkname = models.ManyToManyField(MarketingList, related_name='testfield')


class ChkDbReset(models.Model):
    chk_dbreset = models.CharField(max_length=15)
    chk_dbtime = models.DateTimeField(auto_now_add=True, null=False)

dbmanageapp/views.py
import os
import time
import urllib
from urllib.parse import urlencode, parse_qsl, urlsplit
from datetime import datetime, timedelta
from itertools import chain

import xlwt
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.utils.dateformat import DateFormat

import json
import random
import re

from django.contrib import messages
from django.db.models import Q, Sum
from django.http import JsonResponse, Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy, resolve

from accountapp.models import User
from allmanageapp.models import AllManage
from dbmanageapp.models import MarketingList, UploadDbName, UploadDb, DbSetting, DbMemo, PaidList
from openpyxl import load_workbook

from dateutil.relativedelta import *


def div_dbname(request):
    context = {}

    # 마케팅 리스트 에러 처리 (초기값 셋팅 X)
    try:
        marketing_list = MarketingList.objects.all()
        context['marketing_list'] = marketing_list
    except:
        error = '마케팅 리스트를 추가해주세요!'
        return render(request, 'dbmanageapp/alldblist.html', {'error': error})


    try:
        on_sd_oo = request.GET['sd']
        on_ed_oo = request.GET['ed']
        datetime_format = "%Y-%m-%d"
        on_sd = datetime.strptime(on_sd_oo, datetime_format)
        on_ed = datetime.strptime(on_ed_oo, datetime_format)
        div_date = set_search_day(on_sd, on_ed)
        context['sd'] = on_sd_oo
        context['ed'] = on_ed_oo
    except:
        now_datetime = datetime.today()
        f_datetime = datetime(now_datetime.year, now_datetime.month, 1)
        div_date = set_search_day(f_datetime, now_datetime)

    if request.method == 'POST':
        mk = request.POST.get('mk')
        context['mk'] = mk
        dbname_num = request.POST.getlist('dbname_num[]')
        dbname_id = request.POST.getlist('dbname_id[]')
        get_mk = MarketingList.objects.get(mk_company=mk)

        for val in dbname_num:
            temp_dbname = UploadDbName.objects.get(id=dbname_id[int(val)])
            temp_dbname.dbn_mkname = get_mk
            temp_dbname.save()

    db_name_list = UploadDbName.objects.filter(dbn_date__range=[div_date[0], div_date[1]])
    context['db_name_list'] = db_name_list

    return render(request, 'dbmanageapp/div_dbname.html', context)


def make_excel(request):
    sd = request.POST.get('ex_sd')
    ed = request.POST.get('ex_ed')
    ns = request.POST.get('ex_ns')
    print(ns)


    datetime_format = "%Y-%m-%d"
    onsd = datetime.strptime(sd, datetime_format)
    oned = datetime.strptime(ed, datetime_format)
    set_date = set_search_day(onsd, oned)

    response = HttpResponse(content_type="application/vnd.ms-excel")
    response["Content-Disposition"] = 'attachment;filename*=UTF-8\'\'example.xls'
    wb = xlwt.Workbook(encoding='ansi')  # encoding은 ansi로 해준다.
    ws = wb.add_sheet('sheet1')  # 시트 추가

    all_memo = DbMemo.objects.filter(dm_date__range=[set_date[0], set_date[1]])

    row_num = 0
    col_names = ['마케터', '전화번호', '이름', '나이', '성별', '자산', '담당자', '담당자 닉네임', '상태', '결제금액', '결제상태']

    # 열이름을 첫번째 행에 추가 시켜준다.
    for idx, col_name in enumerate(col_names):
        ws.write(row_num, idx, col_name)

    # 데이터 베이스에서 유저 정보를 불러온다.

    print(set_date[0])
    print(set_date[1])
    print(ns)
    all_db_list = UploadDb.objects.select_related('db_mkname').filter(db_date__range=[set_date[0], set_date[1]], db_status=ns)
    print(all_db_list)

    rows = []
    for dblist in all_db_list:
        chk_memo = all_memo.filter(dm_chkdb=dblist)
        print(dblist)

        try:
            chk_marketer = dblist.db_mkname.mk_company
        except:
            chk_marketer = ""
        print(chk_marketer)

        print(dblist.db_phone)
        set_list = [chk_marketer, dblist.db_phone, dblist.db_member, dblist.db_age, dblist.db_sex, dblist.db_inv,
                    dblist.db_manager, dblist.db_manager_nick, dblist.db_status, dblist.db_paidprice,
                    dblist.db_paidstatus]
        if (chk_memo):
            for chkcount, memo in enumerate(chk_memo):
                if chkcount > 2:
                    break
                else:
                    set_list.append(memo.dm_memos)

        rows.append(set_list)
    # 유저정보를 한줄씩 작성한다.
    for row in rows:
        row_num += 1
        for col_num, attr in enumerate(row):
            ws.write(row_num, col_num, attr)

    wb.save(response)
    return response


def update_db(request):
    chk_db_list = DbMemo.objects.all()
    for dlist in chk_db_list:
        if dlist.dm_manager == "":
            dlist.dm_manager = dlist.dm_chkdb.db_manager
            dlist.save()
    return HttpResponse('완료가 잘 되었는지 봅시다.')


@login_required
def dbmainpage(request):
    q = Q()
    j = Q()
    if not request.user.rete == 'A':
        q.add(Q(db_manager=request.user), q.AND)
        j.add(Q(db_manager=request.user), q.AND)

    now_datetime = datetime.today()
    f_datetime = datetime(now_datetime.year, now_datetime.month, 1)

    last_month_first = datetime(now_datetime.year, now_datetime.month, 1) + relativedelta(months=-1)
    last_month_last = datetime(now_datetime.year, now_datetime.month, 1) + relativedelta(seconds=-1)

    now_month_setdate = set_search_day(f_datetime, now_datetime)
    last_month_setdate = set_search_day(last_month_first, last_month_last)

    q.add(Q(db_date__range=[now_month_setdate[0], now_month_setdate[1]]), q.AND)
    j.add(Q(db_date__range=[last_month_setdate[0], last_month_setdate[1]]), q.AND)

    now_month_price = UploadDb.objects.filter(q)
    last_month_price = UploadDb.objects.filter(j)

    n_sales = now_month_price.aggregate(Sum('db_paidprice'))
    l_sales = last_month_price.aggregate(Sum('db_paidprice'))
    n_sales = n_sales['db_paidprice__sum']
    l_sales = l_sales['db_paidprice__sum']
    i = 0

    if not n_sales or not l_sales:
        growth_per = None
    else:
        growth_per = "%.2f%%" % (n_sales / l_sales * 100.0)

    return render(request, 'dbmanageapp/mainpage.html',
                  {'n_sales': n_sales, 'l_sales': l_sales, 'growth_per': growth_per})


@login_required
def base_setting(request):
    if request.method == 'POST':
        company_name = request.POST.get('company_name')
        upload_img = request.FILES.get('logo_image')
        ds_status = request.POST.get('ds_status')
        ds_statusbase = request.POST.get('ds_statusbase')
        theme_status = request.POST.get('theme_status')
        ds_overlapallow = request.POST.get('ds_overlapallow')

        set_model = DbSetting.objects.last()

        if set_model:
            set_model.company_name = company_name
            set_model.ds_status = ds_status
            set_model.ds_statusbase = ds_statusbase
            set_model.ds_overlapallow = ds_overlapallow
            set_model.theme_status = theme_status
            if upload_img:
                if set_model.logo_image:
                    os.remove(set_model.logo_image.path)
                set_model.logo_image = upload_img
            set_model.save()
            messages.success(request, '성공적으로 반영되었습니다.')
        else:
            dbset = DbSetting()
            dbset.company_name = company_name
            dbset.ds_status = ds_status
            dbset.ds_statusbase = ds_statusbase
            dbset.ds_overlapallow = ds_overlapallow
            dbset.theme_status = theme_status
            if upload_img:
                dbset.logo_image = upload_img
            dbset.save()

    try:
        set_content = DbSetting.objects.last()
        select_menu = set_content.ds_status
        select_menu = select_menu.split(',')
        ontm = set_content.theme_status
    except:
        ontm = ""
        select_menu = ""
    return render(request, 'dbmanageapp/base_setting.html',
                  {'set_content': set_content, 'select_menu': select_menu, 'ot': ontm})


def marketer_stats(request):
    # 마케팅 리스트 에러 처리 (초기값 셋팅 X)
    try:
        marketing_list = MarketingList.objects.all()
    except:
        error = '마케팅 리스트를 추가해주세요!'
        return render(request, 'dbmanageapp/alldblist.html', {'error': error})

    q = Q()
    j = Q()
    geton = get_getlist(request, q, j)

    mk_list = MarketingList.objects.all()
    mk_list_value = MarketingList.objects.values()
    ii = 0
    mk_on_list = []

    for mlist in mk_list:
        paid_a_sum = 0

        mk_on_list.append(mk_list_value[ii])
        # 검색된 날짜 기준에 등록된 DB의 전체 리스트 (전체 등록건)
        all_dblist = mlist.dbmkname.filter(db_date__range=[geton['set_date'][0], geton['set_date'][1]])

        # 검색된 날짜 기준에 등록된 DB이름에 기재된 DB 값들의 합
        seach_dbname_for_spend_db = mlist.mkdname.filter(dbn_date__range=[geton['set_date'][0], geton['set_date'][1]])
        spend_db = seach_dbname_for_spend_db.aggregate(Sum('dbn_price'))

        # 검색된 날짜 기준에 마지막 결제일이 포함되어 있는 DB의 리스트 (누적 결제건)
        paid_dblist = mlist.dbmkname.filter(db_lastpaiddate__range=[geton['set_date'][0], geton['set_date'][1]],
                                            db_paidstatus='Y')
        for dlist in paid_dblist:
            # 검색된 DB의 이번달 내지 검색된 날짜 기준으로 결제된 금액을 구함
            inner_paid_list = dlist.plchkdb.filter(pl_paiddate__range=[geton['set_date'][0], geton['set_date'][1]])
            for pilist in inner_paid_list:
                paid_a_sum = paid_a_sum + pilist.pl_paidprice

        # 누적 결제금
        all_count = all_dblist.count()
        paid_count = paid_dblist.count()
        mk_on_list[ii]['all_count'] = all_count
        mk_on_list[ii]['acc_count'] = len(paid_dblist)
        if paid_count > 0:
            mk_on_list[ii]['acc_per'] = "%.2f%%" % (paid_count / all_count * 100.0)
        else:
            mk_on_list[ii]['acc_per'] = '0%'
        mk_on_list[ii]['acc_price'] = paid_a_sum

        if paid_count > 0:
            acc_aver = paid_a_sum // paid_count
            mk_on_list[ii]['acc_aver'] = acc_aver

dbmanageapp/templates/dbmanageapp/div_dbname.html
{% extends 'db_base.html' %}

{% block dbmanage_content %}

<div id="layoutSidenav_content">
  <main>


    <div class="container">
      <!-- 검색 -->
      <form action="" method="get">
        <div class="pt-4">
          <div class="inputlist">
            <div class="inputflex">
              <div class="center_text">
                <input type="date" name="sd" value="{{ sd }}" class="currentDate_sd">
              </div>
              <div class="center_text">
                <span>~</span>
              </div>

              <div class="center_text">
                <input type="date" name="ed" value="{{ ed }}" class="currentDate_ed">
              </div>
            </div>

            <div class="inputflex">
              <div class="">
                <button class="button is-small is-link">검색</button>
              </div>
            </div>
          </div>



        </div>
      </form>
      <!-- 검색끝 -->

      <form class="" method="post">
        {% csrf_token %}

        <span style="display:inline-block; padding-top:4px;">마케팅리스트 : &nbsp;</span>
        <div class="select is-info is-small">
          <select name="mk" class="mk">
              <option value="">전체선택</option>
              {% for mlist in marketing_list %}
              <option value="{{ mlist.mk_company }}"
                      {% if mlist.mk_company == mk %}
                      selected="selected"
                      {% endif %}>{{ mlist.mk_company }}
              </option>
              {% endfor %}
          </select>
        </div>
        <button class="button is-small is-success submit_btn">변경하기</button>
        <!--        분배 전 DB 리스트-->
        <div class="col-12 mt-5">
          <table class="type07">
            <tr>
              <th>
                <input type="checkbox" name="" value="" class="allchk">
              </th>
              <th>DB명</th>
              <th>등록일</th>
              <th>마케터</th>
            </tr>


            {% for dbname in db_name_list %}
            <tr>
              <td>
                <input type="checkbox" name="dbname_num[]" class="dbname_num" value="{{ forloop.counter0 }}">
                <input type="hidden" name="dbname_id[]" value="{{ dbname.id }}">
              </td>
              <td>{{ dbname.dbn_name }}</td>
              <td>{{ dbname.dbn_date }}</td>
              <td>{{ dbname.dbn_mkname.mk_company }}</td>
            </tr>
            {% endfor %}

          </table>
        </div>
      </form>

    </div>



  </main>

  <script type="text/javascript">
    $('.submit_btn').click(function(){
      var mk = document.querySelector('.mk').value
      if(!mk){
        alert('변경하실 마케터를 선택해주세요!')
        return false
      }
    })

    $('.allchk').change(function(){
      console.log();
      if(this.checked == true){
        $('.dbname_num').attr('checked', true)
      }else{
        $('.dbname_num').attr('checked', false)
      }
    })
  </script>

  {% if not sd %}
  <script !src="">
    var t_date = new Date()
    var t_date = new Date(t_date.getFullYear(), t_date.getMonth(), 1);
    t_date.setHours(t_date.getHours()+9)
    var dateval = t_date.toISOString().substring(0, 10)
    $('.currentDate_sd').val(dateval)

  </script>
  {% endif %}

  {% if not ed %}
  <script !src="">
    var t_date = new Date()
    t_date.setHours(t_date.getHours()+9)
    var dateval = t_date.toISOString().substring(0, 10)
    $('.currentDate_ed').val(dateval)
  </script>
  {% endif %}


  {% endblock %}

dbmanageapp/templates/dbmanageapp/emp_dbstats.html
{% extends 'db_base.html' %}

{% block dbmanage_content %}
{% load humanize %}

<style>
    .payment_wrap{}
    .payment_list{display:none;}
    .payment_toggle{cursor:pointer}
    .payment_on{display:flex; justify-content:center;}
</style>


<div id="layoutSidenav_content">
    <main>
        <div class="container">

            <!-- 검색 -->
            <div class="pt-4">
                <form action="" method="get">
                    <div class="inputlist">

                        <div class="inputflex">
                            <div class="center_text">
                                <input type="date" name="sd" value="{{ get_list.sd }}" class="currentDate_sd">
                            </div>
                            <div class="center_text">
                                <span>~</span>
                            </div>

                            <div class="center_text">
                                <input type="date" name="ed" value="{{ get_list.ed }}" class="currentDate_ed">
                            </div>
                        </div>

                        <div class="inputflex">
                            <div class="center_text">
                                <span>갯수 :</span>
                            </div>

                            <div class="select is-small">
                                <select name="wp">
                                    <option value="10"
                                            {% if get_list.wp == '10' %}selected="selected" {% endif %}>
                                    10
                                    </option>
                                    <option value="20"
                                            {% if get_list.wp == '20' %}selected="selected" {% endif %}>
                                    20
                                    </option>
                                    <option value="50"
                                            {% if get_list.wp == '50' %}selected="selected" {% endif %}>
                                    50
                                    </option>
                                </select>
                            </div>
                        </div>

                        <div class="inputflex">
                            <input type="text" class="input is-link is-small" name="ps" value="{{ get_list.ps }}" id="" placeholder="전화번호 입력">
                            <button class="button is-small is-link">검색</button>
                        </div>

                        <a href="{% url 'dbmanage:sale_st' %}" class="button is-small is-warning">초기화</a>
                    </div>


            </div>
            </form>

            <!-- ******************************검색끝 -->


            <!-- **************************결과값 출력 -->

            <div class="mt-5 table_wrap">
                {% for message in messages %}
                <span
                        {% if message.tags %} class="{{ message.tags }} tag is-danger mb-2" {% endif %}>{{ message }}</span>
                {% endfor %}

                <div class="table_area">
                    <table class="type07">
                        <tr>
                            <th>이름</th>
                            <th>전화번호</th>
                            <th>결제상태</th>
                            <th>결제금액</th>
                            <th>결제건수</th>
                            <th>담당자</th>
                            <th>마케터</th>
                            <th>결제일</th>
                        </tr>

                        {% for dlist in base_db %}

                        <tr>
                            <td>
                                <a class="detail_customer" href="{% url 'dbmanage:detail_customer' id=dlist.id %}"
                                   onclick="window.open(this.href,'회원정보','width=800, height=800'); return false;">
                                    <span>{{ dlist.db_member }}</span>
                                </a>
                            </td>
                            <td> <span class="phnum">{{ dlist.db_phone }}</span></td>
                            <td>{{ dlist.db_paidstatus }}</td>
                            <td>{{ dlist.db_paidprice|intcomma }}원</td>
                            <td>
                                <div class="payment_wrap">
                                    <span>{{ dlist.plchkdb.all.count }}건 / </span> <span class="payment_toggle">(상세보기)</span>
                                    <div class="payment_list">
                                        {% for plist in dlist.plchkdb.all %}
                                        <div class="payment_on">
                                            <div>{{ plist.pl_paidprice|intcomma }}원&nbsp;/&nbsp;</div>
                                            <div> {{ plist.pl_paiddate|date:"m.d h:i" }}</div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>


                            </td>
                            <td>{{ dlist.db_manager_nick }}</td>
                            <td>{{ dlist.db_mkname.mk_company }}</td>
                            <td>{{ dlist.db_lastpaiddate|date:'y-m-d H:i' }}</td>
                        </tr>
                        {% endfor %}


                    </table>
                </div>

            </div>

            <div class="mt-3">
                <table class="type07">
                    <tr>
                        <th>결제 합계</th>
                        <td>{{ sum.db_paidprice__sum|intcomma }}원</td>
                    </tr>
                </table>
            </div>

            <nav class="pagination mt-2" role="navigation" aria-label="pagination">
                <ul class="pagination-list" style="justify-content:center;">
                    {% for paging in pageval %}

                    {% if paging == get_page_num %}
                    <li>
                        <a class="pagination-link is-current ch_a" aria-current="page">{{ paging }}</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="pagination-link ch_a" href="?page={{ paging }}">{{ paging }}</a>
                    </li>
                    {% endif %}

                    {% endfor %}
                </ul>
            </nav>

            <!--        ************************결과값 출력 끝-->


        </div>


    </main>
    <script !src="">

    $('.payment_toggle').click(function(){
        console.log()
        $(this.nextElementSibling).toggle()
    })
    //$(document).click(function(){
    //   $('.payment_list').hide()
    //})

    var phnum = document.querySelectorAll('.phnum')
    for (var i = 0; i < phnum.length; i++) {
        var tempval = phnum[i].innerText
        var tempval = phoneformat(tempval)
        $(phnum[i]).empty()
        $(phnum[i]).append(tempval)
    }

    function phoneformat(num){
        return num.replace(/(^02.{0}|^01.{1}|^[0-9]{3})([0-9]*)([0-9]{4})/, "$1-$2-$3");
    }

     var search = location.search.substring(1);
        var searchObj = JSON.parse('{"' + decodeURI(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}');
        var objtoarr = Object.entries(searchObj)
        var href_val = ""
        for (var i = 0; i < objtoarr.length; i++) {
            if(objtoarr[i][0] == 'page'){
                continue
            }
            var test = objtoarr[i].join('=')
            if(i == 0){
                href_val += "?"
            } else {
                href_val += "&"
            }
            href_val += test
        }

    </script>
    {% for paging in pageval %}
    <script !src="">
    if(href_val){
        var page_num = {{ forloop.counter0 }}
        var paging = {{ paging }}

        var ii = $('.ch_a').eq(page_num).attr("href", href_val+"&page="+paging)
    }

    </script>
    {% endfor %}


    {% if not get_list.sd %}
    <script !src="">
        var t_date = new Date()
        var t_date = new Date(t_date.getFullYear(), t_date.getMonth(), 1);
        t_date.setHours(t_date.getHours()+9)
        var dateval = t_date.toISOString().substring(0, 10)
        $('.currentDate_sd').val(dateval)

    </script>
    {% endif %}

    {% if not get_list.ed %}
    <script !src="">
        var t_date = new Date()
        t_date.setHours(t_date.getHours()+9)
        var dateval = t_date.toISOString().substring(0, 10)
          $('.currentDate_ed').val(dateval)

    </script>
    {% endif %}


    <script !src="">



    </script>
    {% endblock %}

dbmanageapp/templates/dbmanageapp/test_chk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>