accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp import views

app_name = 'accountapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/', views.testpage, name='testpage'),
]

dbmanageapp/urls.py
from django.urls import path

from dbmanageapp import views

app_name = 'dbmanage'
urlpatterns = [
    path('', views.dbmainpage, name='mainpage'),
    path('accountmanagement/', views.accountmanagement, name='accountmanagement'),
    path('markterlist/', views.markerlist, name='markerlist'),
    path('newdbup/', views.newdbup, name='newdbup'),
    path('new_dbup/', views.new_dbup, name='new_dbup'),
    path('divdb/', views.divdb, name='divdb'),
    path('alldblist/', views.alldblist, name='alldblist'),
    path('sale_st/', views.sale_st, name='sale_st'),
    path('detail_customer/<int:id>', views.detail_customer, name='detail_customer'),
    path('workajax/', views.workAjax, name='workajax'),

    path('emp_dblist/', views.emp_dblist, name='emp_dblist'),
    path('div_dbname/', views.div_dbname, name='div_dbname'),
    path('emp_dbstats/', views.emp_dbstats, name='emp_dbstats'),
    path('base_setting/', views.base_setting, name='base_setting'),
    path('marketer_stats/', views.marketer_stats, name='marketer_stats'),
    path('test_chk/', views.test_chk, name='test_chk'),
    path('status_stats/', views.status_stats, name='status_stats'),
    path('updatedb/', views.update_db, name='updatedb'),
    path('make_excel/', views.make_excel, name='make_excel'),

]

handledb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dbmanageapp import views

urlpatterns = [
    path('', views.dbmainpage, name='home'),
    path('adminchangi/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('dbmanager/', include('dbmanageapp.urls')),
    path('super_adm/', include('allmanageapp.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account_base.html
{% include 'account_head.html' %}

{% block accountcontent %}
{% endblock %}

</body>
</html>

templates/account_head.html
<!DOCTYPE html>

{% load static %}

<html lang="ko">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ test }}</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>

    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link href="{% static 'base_style.css' %}" rel="stylesheet"/>
</head>
<body>

templates/db_base.html
{% include 'db_head.html' %}
{% include 'db_header.html' %}

{% block dbmanage_content %}
{% endblock %}

{% include 'db_footer.html' %}

templates/db_footer.html
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid px-4">
    <div class="d-flex align-items-center justify-content-between small">
      <div class="text-muted">Copyright &copy; DreamMore 2022</div>
      <div>
        <a href="#">Privacy Policy</a>
        &middot;
        <a href="#">Terms &amp; Conditions</a>
      </div>
    </div>
  </div>
</footer>
</div>
</div>



<script type="text/javascript">


$('#layoutSidenav_content').click(function(){
  var onwidth = document.body.offsetWidth
  if(onwidth < 992){
    document.body.classList.remove('sb-sidenav-toggled');
  }
})

$('#sidebarToggle').click(function(){
  document.body.classList.toggle('sb-sidenav-toggled');
  localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
})





</script>
</body>

templates/db_head.html
<!DOCTYPE html>

{% load static %}

<html lang="ko">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>어드민 어드민</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />

        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <link href="{% static 'base_style.css' %}?v={{ base_time }}" rel="stylesheet"/>
        <link href="{% static 'dbstyle.css' %}?v={{ base_time }}" rel="stylesheet"/>
</head>

templates/db_header.html
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-0 ms-2 ms-lg-5" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Brand-->

    {% if base_logo %}

    <a href="{% url 'home' %}" id="logo_image_area" style="max-width:120px; margin:0 20px;">
        <img src="{{ base_logo.url }}" alt="">
    </a>
    {% else %}
    <a class="navbar-brand ps-3" href="{% url 'home' %}">Logo</a>
    {% endif %}


    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">회원정보(준비중)</a></li>
                <li>
                    <hr class="dropdown-divider"/>
                </li>
                <li><a class="dropdown-item" href="{% url 'accountapp:logout' %}">로그아웃</a></li>
            </ul>
        </li>
    </ul>

    {% if request.user.is_authenticated %}
    <span style="color:white; display:inline-block;" class="mr-5 mr-md-1">{{ request.user.nickname }}님 </span> <span class="d-none d-md-inline" style="color:white;">반갑습니다</span>
    {% endif %}
</nav>

<!--sb-sidenav-light-->
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">

        {% if base_theme == 'dark' %}
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        {% else %}
        <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
        {% endif %}
            <div class="sb-sidenav-menu">
                <div class="nav">
                    {% if request.user.rete == "A" %}
                    <div class="sb-sidenav-menu-heading">관리자 메뉴</div>
                    <a class="nav-link" href="{% url 'dbmanage:base_setting' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-gear"></i></div>
                        기본 설정
                    </a>
                    <a class="nav-link" href="{% url 'dbmanage:accountmanagement' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        전체 계정관리
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:markerlist' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-clipboard-list"></i></div>
                        마케터 리스트
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:newdbup' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-file-circle-plus"></i></div>
                        신규DB 등록
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:divdb' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-land-mine-on"></i></div>
                        DB 분배
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:alldblist' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-list-check"></i></div>
                        전체 DB 리스트
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:sale_st' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-signal"></i></div>
                        결제리스트
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:status_stats' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-signal"></i></div>
                        관리 통계
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:marketer_stats' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-signal"></i></div>
                        마케터 통계
                    </a>
                    {% endif %}

                    <div class="sb-sidenav-menu-heading">직원 메뉴</div>
                    <a class="nav-link" href="{% url 'dbmanage:emp_dblist' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        DB 리스트
                    </a>

                    <a class="nav-link" href="{% url 'dbmanage:emp_dbstats' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-signal"></i></div>
                        결제리스트
                    </a>


                </div>

            </div>
            <div class="sb-sidenav-footer">

                {% if base_company_name %}
                <div class="small">certified as</div>
                {{ base_company_name }}
                {% else %}
                회사명을 설정하세요
                {% endif %}
            </div>
        </nav>
    </div>

    <script type="text/javascript">
var om_param = getParameterByName('om'); // 1060192
if(om_param == 'on'){
  $('#collapseLayouts').addClass('show')
}
var om_param = getParameterByName('mm'); // 1060192
if(om_param == 'on'){
  $('#collapsePages').addClass('show')
}



function getParameterByName(name) {
  name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
  var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
  results = regex.exec(location.search);
  return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}


    </script>